import type { MetricDefinition } from "@/lib/context/types";

export const CALIDAD_METRICS: MetricDefinition[] = [
  {
    id: "component-health-score",
    name: "Component health score",
    shortName: "Health score",
    contextId: "design-systems",
    attributes: { categoria: "calidad", measurementType: "hybrid", sourcePrimary: "code", figmaAvailability: "partial", maturity: "advanced", signalQuality: "medium", aiRelated: false },
    ficha: {
      description: "Índice compuesto que resume el estado de salud de cada componente (documentación, tests, accesibilidad, bugs y adopción).",
      whyItMatters: "Da una lectura rápida de qué componentes son fiables y cuáles necesitan inversión antes de escalar el sistema.",
      howToMeasure: ["Ponderar señales por componente: cobertura de docs, tests, issues abiertos, a11y y adopción", "Normalizar a un score 0-100 y revisar tendencia"],
      frecuencia: "Mensual", esfuerzo: "Alto", confianza: "Media",
      cruzarCon: ["Cobertura de documentación", "Cobertura de tests", "Accesibilidad del sistema", "Bugs UI en QA"],
      risksBiases: ["La ponderación es subjetiva y puede ocultar problemas concretos tras un promedio"],
      audience: ["DS Team", "Engineering"],
      decision: "Priorizar qué componentes refactorizar o retirar según su salud.",
    },
    tags: ["quality", "components", "health"], relatedMetricIds: ["documentation-coverage", "test-coverage", "system-accessibility"], icon: "HeartPulse", priority: 9,
  },
  {
    id: "documentation-coverage",
    name: "Cobertura de documentación",
    shortName: "Docs",
    contextId: "design-systems",
    attributes: { categoria: "calidad", measurementType: "quantitative", sourcePrimary: "code", figmaAvailability: "no", maturity: "classical", signalQuality: "strong", aiRelated: false },
    ficha: {
      description: "Porcentaje de componentes del sistema con documentación completa (uso, props, ejemplos y guías de accesibilidad).",
      whyItMatters: "Sin documentación, el equipo pregunta o improvisa, lo que dispara el uso incorrecto y el retrabajo.",
      howToMeasure: ["Contar componentes con página de documentación publicada frente al total", "Verificar que incluyan props, do/don't y ejemplos vivos"],
      frecuencia: "Mensual", esfuerzo: "Bajo", confianza: "Alta",
      cruzarCon: ["Component health score", "Tasa de reutilización", "Velocidad de onboarding"],
      risksBiases: ["Documentar no garantiza calidad ni que esté actualizada"],
      audience: ["DS Team", "Design", "Engineering"],
      decision: "Cerrar huecos de documentación en los componentes más usados.",
    },
    tags: ["quality", "documentation"], relatedMetricIds: ["component-health-score", "reuse-rate", "onboarding-speed"], icon: "BookOpen", priority: 7,
  },
  {
    id: "test-coverage",
    name: "Cobertura de tests",
    shortName: "Tests",
    contextId: "design-systems",
    attributes: { categoria: "calidad", measurementType: "quantitative", sourcePrimary: "code", figmaAvailability: "no", maturity: "classical", signalQuality: "strong", aiRelated: false },
    ficha: {
      description: "Porcentaje de componentes cubiertos por tests unitarios, de interacción y de regresión visual.",
      whyItMatters: "Los componentes son dependencias compartidas; un fallo se propaga a todos los consumidores del sistema.",
      howToMeasure: ["Medir cobertura de líneas y ramas por componente", "Incluir tests de regresión visual y de accesibilidad"],
      frecuencia: "Continua", esfuerzo: "Medio", confianza: "Alta",
      cruzarCon: ["Component health score", "Bugs visuales en producción", "Bugs UI en QA"],
      risksBiases: ["Alta cobertura no implica tests significativos ni buenos asserts"],
      audience: ["Engineering", "DS Team"],
      decision: "Añadir tests a los componentes críticos sin cobertura.",
    },
    tags: ["quality", "testing"], relatedMetricIds: ["component-health-score", "visual-bugs-production", "ui-bugs-qa"], icon: "TestTube", priority: 7,
  },
  {
    id: "system-accessibility",
    name: "Accesibilidad del sistema",
    shortName: "A11y",
    contextId: "design-systems",
    attributes: { categoria: "calidad", measurementType: "hybrid", sourcePrimary: "code", figmaAvailability: "partial", maturity: "advanced", signalQuality: "medium", aiRelated: false },
    ficha: {
      description: "Grado de cumplimiento de los componentes con criterios WCAG (contraste, foco, roles ARIA y navegación por teclado).",
      whyItMatters: "La accesibilidad se hereda del sistema; corregirla en la base evita arreglarla producto a producto.",
      howToMeasure: ["Auditar componentes con herramientas automáticas (axe) y revisión manual con lector de pantalla", "Reportar % de criterios WCAG AA cumplidos"],
      frecuencia: "Trimestral", esfuerzo: "Alto", confianza: "Media",
      cruzarCon: ["Component health score", "Consistencia de tokens", "Bugs UI en QA"],
      risksBiases: ["Las herramientas automáticas solo detectan ~40% de los problemas de a11y"],
      audience: ["DS Team", "Design", "Engineering"],
      decision: "Bloquear la publicación de componentes que no cumplan WCAG AA.",
    },
    tags: ["quality", "accessibility"], relatedMetricIds: ["component-health-score", "token-consistency"], icon: "Accessibility", priority: 8,
  },
  {
    id: "ui-bugs-qa",
    name: "Bugs UI en QA",
    shortName: "Bugs QA",
    contextId: "design-systems",
    attributes: { categoria: "calidad", measurementType: "quantitative", sourcePrimary: "support", figmaAvailability: "no", maturity: "classical", signalQuality: "strong", aiRelated: false },
    ficha: {
      description: "Número de defectos de interfaz atribuibles a componentes del sistema detectados durante QA.",
      whyItMatters: "Los bugs originados en el sistema indican dónde falla la calidad antes de llegar a producción.",
      howToMeasure: ["Etiquetar los tickets de QA por componente y origen (sistema vs. producto)", "Contar y tendenciar por release"],
      frecuencia: "Por release", esfuerzo: "Bajo", confianza: "Alta",
      cruzarCon: ["Bugs visuales en producción", "Cobertura de tests", "Incidencias de UI en QA"],
      risksBiases: ["Depende de que QA clasifique correctamente el origen del bug"],
      audience: ["Engineering", "QA", "DS Team"],
      decision: "Reforzar tests en los componentes con más bugs en QA.",
    },
    tags: ["quality", "bugs", "qa"], relatedMetricIds: ["visual-bugs-production", "test-coverage", "ui-incidents-qa"], icon: "Bug", priority: 6,
  },
  {
    id: "visual-bugs-production",
    name: "Bugs visuales en producción",
    shortName: "Bugs prod",
    contextId: "design-systems",
    attributes: { categoria: "calidad", measurementType: "quantitative", sourcePrimary: "support", figmaAvailability: "no", maturity: "classical", signalQuality: "strong", aiRelated: false },
    ficha: {
      description: "Defectos visuales o de comportamiento de componentes del sistema que escapan a QA y llegan a producción.",
      whyItMatters: "Son los fallos más caros y visibles; erosionan la confianza en el sistema y en la marca.",
      howToMeasure: ["Rastrear incidencias en producción etiquetadas por componente", "Calcular tasa de escape frente a bugs detectados en QA"],
      frecuencia: "Continua", esfuerzo: "Bajo", confianza: "Alta",
      cruzarCon: ["Bugs UI en QA", "Cobertura de tests", "Consistencia visual"],
      risksBiases: ["Subregistro: muchos bugs visuales no se reportan formalmente"],
      audience: ["Engineering", "DS Team", "Support"],
      decision: "Introducir regresión visual donde se concentran los escapes a producción.",
    },
    tags: ["quality", "bugs", "production"], relatedMetricIds: ["ui-bugs-qa", "test-coverage", "visual-consistency"], icon: "AlertTriangle", priority: 6,
  },
  {
    id: "visual-consistency",
    name: "Consistencia visual",
    shortName: "Consistencia",
    contextId: "design-systems",
    attributes: { categoria: "calidad", measurementType: "hybrid", sourcePrimary: "figma", figmaAvailability: "yes", maturity: "advanced", signalQuality: "medium", aiRelated: false },
    ficha: {
      description: "Grado en que las pantallas del producto usan estilos, espaciados y patrones coherentes con el sistema.",
      whyItMatters: "La inconsistencia visual hace que el producto parezca de menor calidad y confunde a los usuarios.",
      howToMeasure: ["Auditar muestras de pantallas frente a las guías del sistema", "Medir desviaciones de estilo no justificadas por producto"],
      frecuencia: "Trimestral", esfuerzo: "Alto", confianza: "Media",
      cruzarCon: ["Consistencia de tokens", "Bugs visuales en producción", "Tasa de reutilización"],
      risksBiases: ["La consistencia es en parte subjetiva; depende del criterio del auditor"],
      audience: ["Design", "DS Team"],
      decision: "Alinear las pantallas que más se desvían del lenguaje visual.",
    },
    tags: ["quality", "consistency", "visual"], relatedMetricIds: ["token-consistency", "visual-bugs-production", "reuse-rate"], icon: "Eye", priority: 7,
  },
  {
    id: "token-consistency",
    name: "Consistencia de tokens",
    shortName: "Tokens",
    contextId: "design-systems",
    attributes: { categoria: "calidad", measurementType: "hybrid", sourcePrimary: "code", figmaAvailability: "partial", maturity: "advanced", signalQuality: "strong", aiRelated: false },
    ficha: {
      description: "Proporción de valores de diseño (color, tipografía, espaciado) que usan tokens del sistema en lugar de valores hardcodeados.",
      whyItMatters: "Los tokens son la base del theming y la coherencia; los valores sueltos rompen el sistema silenciosamente.",
      howToMeasure: ["Analizar el código en busca de valores literales frente a referencias a tokens", "Contrastar variables de Figma con las del código"],
      frecuencia: "Mensual", esfuerzo: "Medio", confianza: "Alta",
      cruzarCon: ["Paridad diseño-código", "Consistencia visual", "Accesibilidad del sistema"],
      risksBiases: ["Un token mal nombrado o duplicado puede pasar la métrica pero romper la coherencia"],
      audience: ["DS Team", "Engineering", "Design"],
      decision: "Migrar valores hardcodeados a tokens en las zonas con más desviación.",
    },
    tags: ["quality", "tokens", "consistency"], relatedMetricIds: ["design-code-parity", "visual-consistency", "system-accessibility"], icon: "Palette", priority: 8,
  },
  {
    id: "design-code-parity",
    name: "Paridad diseño-código",
    shortName: "Paridad",
    contextId: "design-systems",
    attributes: { categoria: "calidad", measurementType: "hybrid", sourcePrimary: "figma", figmaAvailability: "partial", maturity: "advanced", signalQuality: "medium", aiRelated: false },
    ficha: {
      description: "Mide si lo diseñado en Figma y lo implementado en código siguen el mismo sistema (props, variantes y tokens).",
      whyItMatters: "Sin paridad, las librerías de diseño y código divergen y el sistema pierde credibilidad.",
      howToMeasure: ["Auditoría Figma vs. código componente a componente", "Comparación de props, variantes y tokens equivalentes"],
      frecuencia: "Trimestral", esfuerzo: "Alto", confianza: "Media",
      cruzarCon: ["Consistencia de tokens", "Cobertura de componentes codificados"],
      risksBiases: ["Difícil de automatizar; depende de auditoría manual"],
      audience: ["DS Team", "Engineering"],
      decision: "Detectar dónde se rompe la equivalencia diseño-código.",
    },
    tags: ["quality", "alignment", "code"], relatedMetricIds: ["token-consistency", "coded-component-coverage"], icon: "GitCompare", priority: 5,
  },
  {
    id: "component-duplication",
    name: "Duplicidad de componentes",
    shortName: "Duplicidad",
    contextId: "design-systems",
    attributes: { categoria: "calidad", measurementType: "quantitative", sourcePrimary: "code", figmaAvailability: "partial", maturity: "classical", signalQuality: "medium", aiRelated: false },
    ficha: {
      description: "Número de componentes que resuelven la misma necesidad de forma redundante en el código o en Figma.",
      whyItMatters: "La duplicidad fragmenta el sistema, multiplica el mantenimiento y genera experiencias divergentes.",
      howToMeasure: ["Detectar componentes con nombre o función equivalente", "Revisar variantes locales que reimplementan patrones del sistema"],
      frecuencia: "Trimestral", esfuerzo: "Medio", confianza: "Media",
      cruzarCon: ["Tasa de reutilización", "Paridad diseño-código", "Consistencia visual"],
      risksBiases: ["Diferenciar duplicado real de variante legítima requiere criterio experto"],
      audience: ["DS Team", "Engineering"],
      decision: "Consolidar o retirar los componentes duplicados.",
    },
    tags: ["quality", "components", "duplication"], relatedMetricIds: ["reuse-rate", "design-code-parity", "visual-consistency"], icon: "Copy", priority: 5,
  },
];
