import type { MetricDefinition } from "@/lib/context/types";

export const DELIVERY_METRICS: MetricDefinition[] = [
  {
    id: "time-to-handoff",
    name: "Time to handoff",
    shortName: "T. handoff",
    contextId: "design-systems",
    attributes: { categoria: "delivery", measurementType: "quantitative", sourcePrimary: "product-analytics", figmaAvailability: "partial", maturity: "classical", signalQuality: "medium", aiRelated: false },
    ficha: {
      description: "Tiempo que transcurre desde que un diseño se da por terminado hasta que se entrega a desarrollo listo para implementar.",
      whyItMatters: "Un handoff lento retrasa toda la cadena de entrega y suele revelar fricción en la fase de especificación.",
      howToMeasure: ["Medir el tiempo entre el estado 'listo para dev' y la entrega efectiva", "Segmentar por tipo de pantalla y equipo"],
      frecuencia: "Por sprint", esfuerzo: "Medio", confianza: "Media",
      cruzarCon: ["Time to market", "Handoffs con componentes codificados", "Reducción de retrabajo"],
      risksBiases: ["Depende de que los estados del flujo se registren de forma consistente"],
      audience: ["Design", "Engineering", "PM"],
      decision: "Reducir la fricción en la fase que más alarga el handoff.",
    },
    tags: ["delivery", "handoff", "speed"], relatedMetricIds: ["time-to-market", "handoffs-with-coded-components", "rework-reduction"], icon: "Timer", priority: 7,
  },
  {
    id: "time-to-market",
    name: "Time to market",
    shortName: "TTM",
    contextId: "design-systems",
    attributes: { categoria: "delivery", measurementType: "quantitative", sourcePrimary: "product-analytics", figmaAvailability: "no", maturity: "classical", signalQuality: "medium", aiRelated: false },
    ficha: {
      description: "Tiempo total desde que se concibe una funcionalidad hasta que llega a producción.",
      whyItMatters: "Es la métrica de negocio que justifica la inversión en el sistema: entregar valor antes.",
      howToMeasure: ["Medir el ciclo completo idea → diseño → desarrollo → release", "Comparar features que usan el sistema frente a las que no"],
      frecuencia: "Por release", esfuerzo: "Medio", confianza: "Media",
      cruzarCon: ["Time to handoff", "Tiempo de desarrollo por patrón", "Cobertura de componentes codificados"],
      risksBiases: ["Muchos factores ajenos al sistema influyen en el time to market"],
      audience: ["PM", "Leadership", "DS Team"],
      decision: "Demostrar el impacto del sistema en la velocidad de entrega.",
    },
    tags: ["delivery", "speed", "business"], relatedMetricIds: ["time-to-handoff", "dev-time-per-pattern", "coded-component-coverage"], icon: "Rocket", priority: 8,
  },
  {
    id: "design-time-per-screen",
    name: "Tiempo medio de diseño por pantalla",
    shortName: "T. diseño",
    contextId: "design-systems",
    attributes: { categoria: "delivery", measurementType: "quantitative", sourcePrimary: "figma", figmaAvailability: "partial", maturity: "classical", signalQuality: "medium", aiRelated: false },
    ficha: {
      description: "Tiempo medio que tarda un diseñador en producir una pantalla usando los componentes del sistema.",
      whyItMatters: "El sistema debe acelerar el diseño; un tiempo alto sugiere componentes insuficientes o mal documentados.",
      howToMeasure: ["Estimar horas de diseño por pantalla en una muestra representativa", "Comparar pantallas con alto y bajo uso de componentes del sistema"],
      frecuencia: "Trimestral", esfuerzo: "Medio", confianza: "Baja",
      cruzarCon: ["Tasa de reutilización", "Cobertura de documentación", "Time to handoff"],
      risksBiases: ["El tiempo de diseño es difícil de medir con precisión y varía mucho por complejidad"],
      audience: ["Design", "DS Team"],
      decision: "Crear los componentes que más aceleran el diseño de pantallas.",
    },
    tags: ["delivery", "design", "speed"], relatedMetricIds: ["reuse-rate", "documentation-coverage", "time-to-handoff"], icon: "Clock", priority: 5,
  },
  {
    id: "dev-time-per-pattern",
    name: "Tiempo de desarrollo por patrón",
    shortName: "T. dev",
    contextId: "design-systems",
    attributes: { categoria: "delivery", measurementType: "quantitative", sourcePrimary: "code", figmaAvailability: "no", maturity: "classical", signalQuality: "medium", aiRelated: false },
    ficha: {
      description: "Tiempo medio que tarda desarrollo en implementar un patrón o pantalla con y sin componentes del sistema.",
      whyItMatters: "Cuantifica el ahorro de ingeniería que aporta el sistema y justifica seguir invirtiendo en él.",
      howToMeasure: ["Medir horas de implementación por patrón en features comparables", "Contrastar uso de componentes codificados frente a implementación a medida"],
      frecuencia: "Trimestral", esfuerzo: "Medio", confianza: "Baja",
      cruzarCon: ["Cobertura de componentes codificados", "Time to market", "Reducción de retrabajo"],
      risksBiases: ["La complejidad del patrón introduce mucha variabilidad entre casos"],
      audience: ["Engineering", "DS Team"],
      decision: "Priorizar componentes codificados para los patrones más costosos.",
    },
    tags: ["delivery", "engineering", "speed"], relatedMetricIds: ["coded-component-coverage", "time-to-market", "rework-reduction"], icon: "Gauge", priority: 6,
  },
  {
    id: "rework-reduction",
    name: "Reducción de retrabajo",
    shortName: "Retrabajo",
    contextId: "design-systems",
    attributes: { categoria: "delivery", measurementType: "hybrid", sourcePrimary: "product-analytics", figmaAvailability: "no", maturity: "advanced", signalQuality: "medium", aiRelated: false },
    ficha: {
      description: "Disminución del trabajo repetido (rediseños, reimplementaciones, correcciones) atribuible al uso del sistema.",
      whyItMatters: "El retrabajo es coste puro; reducirlo es una de las promesas centrales de un design system.",
      howToMeasure: ["Rastrear tickets y tareas marcadas como rework antes y después de adoptar el sistema", "Estimar horas evitadas por reutilización"],
      frecuencia: "Trimestral", esfuerzo: "Alto", confianza: "Media",
      cruzarCon: ["Tasa de reutilización", "Incidencias de UI en QA", "Tiempo de desarrollo por patrón"],
      risksBiases: ["Atribuir el ahorro exclusivamente al sistema es difícil de aislar"],
      audience: ["DS Team", "Leadership", "Engineering"],
      decision: "Justificar la inversión en el sistema con el retrabajo evitado.",
    },
    tags: ["delivery", "efficiency", "rework"], relatedMetricIds: ["reuse-rate", "ui-incidents-qa", "dev-time-per-pattern"], icon: "Recycle", priority: 7,
  },
  {
    id: "ui-incidents-qa",
    name: "Incidencias de UI en QA",
    shortName: "Incid. QA",
    contextId: "design-systems",
    attributes: { categoria: "delivery", measurementType: "quantitative", sourcePrimary: "support", figmaAvailability: "no", maturity: "classical", signalQuality: "strong", aiRelated: false },
    ficha: {
      description: "Volumen de incidencias de interfaz abiertas durante QA que retrasan la entrega de una release.",
      whyItMatters: "Las incidencias de UI en QA frenan el delivery; un sistema sólido debería reducir su frecuencia.",
      howToMeasure: ["Contar incidencias de UI por release y su tiempo de resolución", "Separar las originadas en el sistema de las del producto"],
      frecuencia: "Por release", esfuerzo: "Bajo", confianza: "Alta",
      cruzarCon: ["Bugs UI en QA", "Reducción de retrabajo", "Cobertura de componentes codificados"],
      risksBiases: ["Se solapa con métricas de calidad; requiere clasificar bien el origen"],
      audience: ["QA", "Engineering", "PM"],
      decision: "Actuar sobre las incidencias que más retrasan las releases.",
    },
    tags: ["delivery", "qa", "incidents"], relatedMetricIds: ["ui-bugs-qa", "rework-reduction", "coded-component-coverage"], icon: "AlertTriangle", priority: 5,
  },
  {
    id: "handoffs-with-coded-components",
    name: "Handoffs con componentes codificados",
    shortName: "Handoffs cod.",
    contextId: "design-systems",
    attributes: { categoria: "delivery", measurementType: "quantitative", sourcePrimary: "figma", figmaAvailability: "partial", maturity: "advanced", signalQuality: "medium", aiRelated: false },
    ficha: {
      description: "Proporción de handoffs en los que los componentes diseñados ya tienen equivalente codificado listo para usar.",
      whyItMatters: "Cuando el handoff se apoya en componentes ya codificados, la implementación es más rápida y fiel.",
      howToMeasure: ["Revisar en cada handoff qué componentes tienen su par codificado y mapeado (p. ej. Code Connect)", "Calcular el porcentaje sobre el total de handoffs"],
      frecuencia: "Por sprint", esfuerzo: "Medio", confianza: "Media",
      cruzarCon: ["Cobertura de componentes codificados", "Time to handoff", "Paridad diseño-código"],
      risksBiases: ["Un componente codificado desactualizado puede contarse como positivo sin serlo"],
      audience: ["Design", "Engineering", "DS Team"],
      decision: "Aumentar la cobertura codificada de los componentes más presentes en handoffs.",
    },
    tags: ["delivery", "handoff", "code"], relatedMetricIds: ["coded-component-coverage", "time-to-handoff", "design-code-parity"], icon: "PackageCheck", priority: 6,
  },
  {
    id: "coded-component-coverage",
    name: "Cobertura de componentes codificados",
    shortName: "Cobertura cod.",
    contextId: "design-systems",
    attributes: { categoria: "delivery", measurementType: "quantitative", sourcePrimary: "code", figmaAvailability: "partial", maturity: "classical", signalQuality: "strong", aiRelated: false },
    ficha: {
      description: "Porcentaje de componentes del sistema de diseño que cuentan con una implementación en código disponible y mantenida.",
      whyItMatters: "La cobertura codificada determina cuánto del sistema puede realmente reutilizar desarrollo.",
      howToMeasure: ["Contar componentes de la librería de diseño con par en la librería de código", "Verificar que estén publicados y versionados"],
      frecuencia: "Mensual", esfuerzo: "Bajo", confianza: "Alta",
      cruzarCon: ["Handoffs con componentes codificados", "Paridad diseño-código", "Tasa de reutilización"],
      risksBiases: ["Existir en código no garantiza que esté actualizado ni que se use"],
      audience: ["DS Team", "Engineering"],
      decision: "Codificar los componentes diseñados que aún no tienen implementación.",
    },
    tags: ["delivery", "coverage", "code"], relatedMetricIds: ["handoffs-with-coded-components", "design-code-parity", "reuse-rate"], icon: "Boxes", priority: 8,
  },
  {
    id: "reuse-rate",
    name: "Tasa de reutilización",
    shortName: "Reutilización",
    contextId: "design-systems",
    attributes: { categoria: "delivery", measurementType: "quantitative", sourcePrimary: "code", figmaAvailability: "partial", maturity: "classical", signalQuality: "strong", aiRelated: false },
    ficha: {
      description: "Proporción de la interfaz construida con componentes del sistema frente a implementaciones a medida.",
      whyItMatters: "La reutilización es el mejor indicador de que el sistema aporta valor real y está siendo adoptado.",
      howToMeasure: ["Analizar el código para medir instancias de componentes del sistema sobre el total de UI", "Segmentar por producto y equipo"],
      frecuencia: "Mensual", esfuerzo: "Medio", confianza: "Alta",
      cruzarCon: ["Cobertura de componentes codificados", "Reducción de retrabajo", "Duplicidad de componentes"],
      risksBiases: ["Una tasa alta puede ocultar componentes forzados o mal ajustados a la necesidad"],
      audience: ["DS Team", "Engineering", "Leadership"],
      decision: "Impulsar la adopción en los productos con menor reutilización.",
    },
    tags: ["delivery", "adoption", "reuse"], relatedMetricIds: ["coded-component-coverage", "rework-reduction", "component-duplication"], icon: "Repeat", priority: 9,
  },
  {
    id: "onboarding-speed",
    name: "Velocidad de onboarding",
    shortName: "Onboarding",
    contextId: "design-systems",
    attributes: { categoria: "delivery", measurementType: "hybrid", sourcePrimary: "research", figmaAvailability: "no", maturity: "classical", signalQuality: "medium", aiRelated: false },
    ficha: {
      description: "Tiempo que necesita una persona nueva (diseño o desarrollo) para ser productiva usando el sistema.",
      whyItMatters: "Un sistema bien documentado y consistente acelera la incorporación y reduce la dependencia de expertos.",
      howToMeasure: ["Medir el tiempo hasta la primera contribución usando el sistema", "Complementar con encuestas de percepción de facilidad de arranque"],
      frecuencia: "Semestral", esfuerzo: "Medio", confianza: "Baja",
      cruzarCon: ["Cobertura de documentación", "Tasa de reutilización", "Tiempo medio de diseño por pantalla"],
      risksBiases: ["Muy influido por la experiencia previa y el acompañamiento del equipo"],
      audience: ["DS Team", "Design", "Engineering"],
      decision: "Mejorar docs y ejemplos donde el onboarding se atasca.",
    },
    tags: ["delivery", "onboarding", "adoption"], relatedMetricIds: ["documentation-coverage", "reuse-rate", "design-time-per-screen"], icon: "GraduationCap", priority: 6,
  },
];
