import type { MetricDefinition } from "@/lib/context/types";

export const IA_METRICS: MetricDefinition[] = [
  {
    id: "automation-success-rate",
    name: "Tasa de éxito de automatización",
    shortName: "Éxito automatización",
    contextId: "design-systems",
    attributes: {
      categoria: "ia",
      measurementType: "quantitative",
      sourcePrimary: "ai-logs",
      figmaAvailability: "no",
      maturity: "advanced",
      signalQuality: "strong",
      aiRelated: true,
    },
    ficha: {
      description: "Proporción de tareas automatizadas con IA que se completan sin intervención manual.",
      whyItMatters: "Mide cuánto trabajo real resuelve la automatización de extremo a extremo.",
      howToMeasure: ["Ratio de ejecuciones exitosas sobre el total", "Segmentación por tipo de tarea"],
      frecuencia: "Mensual",
      esfuerzo: "Medio",
      confianza: "Alta",
      cruzarCon: ["Ratio de corrección post-IA", "Retrabajo post-IA"],
      risksBiases: ["Definir 'éxito' de forma laxa infla la métrica"],
      audience: ["DS Team", "Leadership"],
      decision: "Ampliar automatización en tareas con alta tasa de éxito.",
    },
    tags: ["automation", "success"],
    relatedMetricIds: ["post-ai-correction-ratio", "post-ai-rework"],
    icon: "Workflow",
    priority: 4,
  },
  {
    id: "post-ai-correction-ratio",
    name: "Ratio de corrección post-IA",
    shortName: "Corrección post-IA",
    contextId: "design-systems",
    attributes: {
      categoria: "ia",
      measurementType: "quantitative",
      sourcePrimary: "ai-logs",
      figmaAvailability: "no",
      maturity: "advanced",
      signalQuality: "strong",
      aiRelated: true,
    },
    ficha: {
      description: "Proporción de salidas de IA que requieren corrección manual antes de usarse.",
      whyItMatters: "Cuanta más corrección, menor el ahorro real que aporta la IA.",
      howToMeasure: ["Ratio de outputs editados sobre el total", "Distancia de edición media"],
      frecuencia: "Mensual",
      esfuerzo: "Medio",
      confianza: "Alta",
      cruzarCon: ["Tasa de éxito de automatización", "Retrabajo post-IA"],
      risksBiases: ["Ediciones cosméticas cuentan igual que correcciones sustanciales"],
      audience: ["DS Team"],
      decision: "Mejorar prompts y guardrails donde la corrección es más frecuente.",
    },
    tags: ["ai-quality", "correction"],
    relatedMetricIds: ["automation-success-rate", "post-ai-rework"],
    icon: "RefreshCw",
    priority: 4,
  },
  {
    id: "post-ai-rework",
    name: "Retrabajo post-IA",
    shortName: "Retrabajo IA",
    contextId: "design-systems",
    attributes: {
      categoria: "ia",
      measurementType: "hybrid",
      sourcePrimary: "ai-logs",
      figmaAvailability: "no",
      maturity: "advanced",
      signalQuality: "medium",
      aiRelated: true,
    },
    ficha: {
      description: "Esfuerzo dedicado a rehacer o ajustar entregables generados con IA.",
      whyItMatters: "El retrabajo elevado anula la promesa de productividad de la IA.",
      howToMeasure: ["Tiempo estimado de ajuste por entregable", "Número de iteraciones hasta aprobar"],
      frecuencia: "Mensual",
      esfuerzo: "Alto",
      confianza: "Media",
      cruzarCon: ["Ratio de corrección post-IA", "Tasa de éxito de automatización"],
      risksBiases: ["Estimar el tiempo de retrabajo es subjetivo"],
      audience: ["DS Team", "Design Leads"],
      decision: "Rediseñar los flujos de IA con mayor coste de retrabajo.",
    },
    tags: ["rework", "ai-quality"],
    relatedMetricIds: ["post-ai-correction-ratio", "automation-success-rate"],
    icon: "Repeat",
    priority: 3,
  },
  {
    id: "generative-consistency",
    name: "Consistencia generativa",
    shortName: "Consistencia IA",
    contextId: "design-systems",
    attributes: {
      categoria: "ia",
      measurementType: "experimental",
      sourcePrimary: "ai-logs",
      figmaAvailability: "no",
      maturity: "experimental",
      signalQuality: "speculative",
      aiRelated: true,
    },
    ficha: {
      description: "Grado en que la IA produce salidas alineadas con los tokens y patrones del sistema.",
      whyItMatters: "La IA solo escala el DS si respeta sus reglas de forma fiable.",
      howToMeasure: ["Verificación automática contra tokens del sistema", "Muestreo y revisión experta"],
      frecuencia: "Mensual",
      esfuerzo: "Alto",
      confianza: "Baja",
      cruzarCon: ["Guardrails coverage", "Slop visual ratio"],
      risksBiases: ["Difícil definir un baseline objetivo de consistencia"],
      audience: ["DS Team"],
      decision: "Reforzar guardrails donde la IA se desvía del sistema.",
    },
    tags: ["consistency", "generative"],
    relatedMetricIds: ["guardrails-coverage", "visual-slop-ratio"],
    icon: "Sparkles",
    priority: 3,
  },
  {
    id: "reused-prompts",
    name: "Prompts reutilizados",
    shortName: "Prompts reutilizados",
    contextId: "design-systems",
    attributes: {
      categoria: "ia",
      measurementType: "quantitative",
      sourcePrimary: "ai-logs",
      figmaAvailability: "no",
      maturity: "advanced",
      signalQuality: "medium",
      aiRelated: true,
    },
    ficha: {
      description: "Proporción de prompts que se reutilizan desde una biblioteca compartida.",
      whyItMatters: "La reutilización estandariza resultados y reduce el prompting ad hoc.",
      howToMeasure: ["Ratio de usos de prompts de biblioteca sobre el total", "Top de prompts más reutilizados"],
      frecuencia: "Mensual",
      esfuerzo: "Bajo",
      confianza: "Media",
      cruzarCon: ["Prompts versionados", "Plantillas validadas"],
      risksBiases: ["Alta reutilización de un prompt malo propaga errores"],
      audience: ["DS Team"],
      decision: "Promover los prompts de biblioteca frente al prompting improvisado.",
    },
    tags: ["prompts", "reuse"],
    relatedMetricIds: ["versioned-prompts", "validated-templates"],
    icon: "GitPullRequestArrow",
    priority: 3,
  },
  {
    id: "versioned-prompts",
    name: "Prompts versionados",
    shortName: "Prompts versionados",
    contextId: "design-systems",
    attributes: {
      categoria: "ia",
      measurementType: "quantitative",
      sourcePrimary: "ai-logs",
      figmaAvailability: "no",
      maturity: "advanced",
      signalQuality: "medium",
      aiRelated: true,
    },
    ficha: {
      description: "Proporción de prompts bajo control de versiones con histórico de cambios.",
      whyItMatters: "El versionado permite trazar regresiones y revertir prompts problemáticos.",
      howToMeasure: ["Ratio de prompts versionados sobre el total", "Frecuencia de cambios registrados"],
      frecuencia: "Mensual",
      esfuerzo: "Medio",
      confianza: "Media",
      cruzarCon: ["Prompts reutilizados", "Guardrails coverage"],
      risksBiases: ["Versionar sin revisar aporta trazabilidad pero no calidad"],
      audience: ["DS Team"],
      decision: "Exigir versionado en los prompts críticos de producción.",
    },
    tags: ["prompts", "versioning"],
    relatedMetricIds: ["reused-prompts", "guardrails-coverage"],
    icon: "FileCheck2",
    priority: 2,
  },
  {
    id: "guardrails-coverage",
    name: "Guardrails coverage",
    shortName: "Guardrails",
    contextId: "design-systems",
    attributes: {
      categoria: "ia",
      measurementType: "quantitative",
      sourcePrimary: "ai-logs",
      figmaAvailability: "no",
      maturity: "advanced",
      signalQuality: "strong",
      aiRelated: true,
    },
    ficha: {
      description: "Proporción de flujos de IA cubiertos por reglas y validaciones automáticas.",
      whyItMatters: "Los guardrails contienen desviaciones antes de que lleguen a producción.",
      howToMeasure: ["Ratio de flujos con guardrails sobre el total", "Reglas activas por flujo"],
      frecuencia: "Mensual",
      esfuerzo: "Medio",
      confianza: "Alta",
      cruzarCon: ["Consistencia generativa", "Slop visual ratio"],
      risksBiases: ["Cobertura alta con reglas débiles da falsa seguridad"],
      audience: ["DS Team", "Leadership"],
      decision: "Extender guardrails a los flujos de IA sin protección.",
    },
    tags: ["guardrails", "governance"],
    relatedMetricIds: ["generative-consistency", "visual-slop-ratio"],
    icon: "ShieldCheck",
    priority: 4,
  },
  {
    id: "validated-templates",
    name: "Plantillas validadas",
    shortName: "Plantillas validadas",
    contextId: "design-systems",
    attributes: {
      categoria: "ia",
      measurementType: "quantitative",
      sourcePrimary: "ai-logs",
      figmaAvailability: "partial",
      maturity: "advanced",
      signalQuality: "medium",
      aiRelated: true,
    },
    ficha: {
      description: "Proporción de plantillas generativas revisadas y aprobadas por el equipo de DS.",
      whyItMatters: "Plantillas validadas garantizan un punto de partida alineado con el sistema.",
      howToMeasure: ["Ratio de plantillas aprobadas sobre el total", "Fecha de última revisión"],
      frecuencia: "Mensual",
      esfuerzo: "Medio",
      confianza: "Media",
      cruzarCon: ["Prompts reutilizados", "Assets generados aceptados"],
      risksBiases: ["Validación caduca si no se revisa al evolucionar el sistema"],
      audience: ["DS Team"],
      decision: "Validar y mantener al día las plantillas más usadas.",
    },
    tags: ["templates", "validation"],
    relatedMetricIds: ["reused-prompts", "accepted-generated-assets"],
    icon: "ClipboardCheck",
    priority: 3,
  },
  {
    id: "accepted-generated-assets",
    name: "Assets generados aceptados",
    shortName: "Assets aceptados",
    contextId: "design-systems",
    attributes: {
      categoria: "ia",
      measurementType: "quantitative",
      sourcePrimary: "ai-logs",
      figmaAvailability: "partial",
      maturity: "advanced",
      signalQuality: "strong",
      aiRelated: true,
    },
    ficha: {
      description: "Proporción de assets generados con IA que se aceptan sin cambios sustanciales.",
      whyItMatters: "Es una señal directa de la utilidad práctica de la generación de assets.",
      howToMeasure: ["Ratio de assets aceptados sobre generados", "Tasa de descarte por motivo"],
      frecuencia: "Mensual",
      esfuerzo: "Bajo",
      confianza: "Alta",
      cruzarCon: ["Ratio de corrección post-IA", "Plantillas validadas"],
      risksBiases: ["Aceptar por falta de tiempo, no por calidad real"],
      audience: ["DS Team", "Design Leads"],
      decision: "Escalar la generación de los tipos de asset con mayor aceptación.",
    },
    tags: ["assets", "acceptance"],
    relatedMetricIds: ["post-ai-correction-ratio", "validated-templates"],
    icon: "PackageCheck",
    priority: 3,
  },
  {
    id: "visual-slop-ratio",
    name: "Slop visual ratio",
    shortName: "Slop visual",
    contextId: "design-systems",
    attributes: {
      categoria: "ia",
      measurementType: "experimental",
      sourcePrimary: "ai-logs",
      figmaAvailability: "no",
      maturity: "experimental",
      signalQuality: "speculative",
      aiRelated: true,
    },
    ficha: {
      description: "Proporción de salidas generativas de baja calidad o incoherentes con el sistema.",
      whyItMatters: "El 'slop' visual erosiona la marca y satura los flujos de revisión.",
      howToMeasure: ["Muestreo y etiquetado experto de slop", "Ratio de descartes por baja calidad"],
      frecuencia: "Mensual",
      esfuerzo: "Alto",
      confianza: "Baja",
      cruzarCon: ["Consistencia generativa", "Guardrails coverage"],
      risksBiases: ["'Slop' es un juicio subjetivo difícil de estandarizar"],
      audience: ["DS Team"],
      decision: "Endurecer guardrails y filtros donde el slop es más alto.",
    },
    tags: ["slop", "ai-quality"],
    relatedMetricIds: ["generative-consistency", "guardrails-coverage"],
    icon: "SprayCan",
    priority: 3,
  },
];
