import type { MetricDefinition } from "@/lib/context/types";

export const SATISFACCION_METRICS: MetricDefinition[] = [
  {
    id: "ds-nps",
    name: "NPS del Design System",
    shortName: "NPS DS",
    contextId: "design-systems",
    attributes: {
      categoria: "satisfaccion",
      measurementType: "qualitative",
      sourcePrimary: "research",
      figmaAvailability: "no",
      maturity: "classical",
      signalQuality: "medium",
      aiRelated: false,
    },
    ficha: {
      description: "Grado en que los equipos recomendarían usar el Design System.",
      whyItMatters: "Resume la percepción global del sistema en una señal comparable en el tiempo.",
      howToMeasure: ["Encuesta NPS periódica a adopters", "Segmentación por rol y squad"],
      frecuencia: "Trimestral",
      esfuerzo: "Medio",
      confianza: "Media",
      cruzarCon: ["Confianza en el sistema", "Fricción de uso"],
      risksBiases: ["Sesgo de respuesta: contestan los más motivados"],
      audience: ["Leadership", "DS Team"],
      decision: "Detectar si la percepción del sistema mejora o empeora.",
    },
    tags: ["nps", "perception"],
    relatedMetricIds: ["adopter-satisfaction", "system-trust"],
    icon: "Star",
    priority: 4,
  },
  {
    id: "adopter-satisfaction",
    name: "Satisfacción de adopters",
    shortName: "Satisfacción",
    contextId: "design-systems",
    attributes: {
      categoria: "satisfaccion",
      measurementType: "qualitative",
      sourcePrimary: "research",
      figmaAvailability: "no",
      maturity: "classical",
      signalQuality: "medium",
      aiRelated: false,
    },
    ficha: {
      description: "Nivel de satisfacción general de quienes consumen el sistema en su día a día.",
      whyItMatters: "Un sistema satisfactorio se adopta por convicción y no por obligación.",
      howToMeasure: ["Encuesta CSAT tras interacciones clave", "Puntuación media por trimestre"],
      frecuencia: "Trimestral",
      esfuerzo: "Bajo",
      confianza: "Media",
      cruzarCon: ["NPS del Design System", "Percepción de velocidad", "Fricción de uso"],
      risksBiases: ["Momento de la encuesta condiciona la respuesta"],
      audience: ["DS Team", "Design Leads"],
      decision: "Priorizar mejoras donde la satisfacción cae por debajo del umbral.",
    },
    tags: ["csat", "satisfaction"],
    relatedMetricIds: ["ds-nps", "usage-friction"],
    icon: "Smile",
    priority: 4,
  },
  {
    id: "system-trust",
    name: "Confianza en el sistema",
    shortName: "Confianza",
    contextId: "design-systems",
    attributes: {
      categoria: "satisfaccion",
      measurementType: "qualitative",
      sourcePrimary: "research",
      figmaAvailability: "no",
      maturity: "classical",
      signalQuality: "medium",
      aiRelated: false,
    },
    ficha: {
      description: "Grado en que los equipos confían en usar los componentes sin revisarlos a fondo.",
      whyItMatters: "La confianza reduce el retrabajo y acelera la adopción de nuevos componentes.",
      howToMeasure: ["Escala de confianza en encuesta", "Preguntas sobre uso directo vs. verificación"],
      frecuencia: "Trimestral",
      esfuerzo: "Medio",
      confianza: "Media",
      cruzarCon: ["Percepción de calidad", "Calidad percibida del soporte"],
      risksBiases: ["La confianza declarada no siempre coincide con el uso real"],
      audience: ["DS Team", "Design Leads"],
      decision: "Reforzar documentación y QA en componentes que generan desconfianza.",
    },
    tags: ["trust", "perception"],
    relatedMetricIds: ["perceived-quality", "ds-nps"],
    icon: "Heart",
    priority: 3,
  },
  {
    id: "perceived-speed",
    name: "Percepción de velocidad",
    shortName: "Velocidad",
    contextId: "design-systems",
    attributes: {
      categoria: "satisfaccion",
      measurementType: "qualitative",
      sourcePrimary: "research",
      figmaAvailability: "no",
      maturity: "classical",
      signalQuality: "weak",
      aiRelated: false,
    },
    ficha: {
      description: "Percepción de cuánto acelera el sistema el trabajo de diseño y desarrollo.",
      whyItMatters: "Uno de los principales argumentos de valor del DS es ahorrar tiempo.",
      howToMeasure: ["Pregunta directa sobre ahorro percibido", "Comparación antes/después de adoptar"],
      frecuencia: "Trimestral",
      esfuerzo: "Bajo",
      confianza: "Baja",
      cruzarCon: ["Satisfacción de adopters", "Fricción de uso"],
      risksBiases: ["Percepción sesgada por casos recientes memorables"],
      audience: ["Leadership", "DS Team"],
      decision: "Comunicar y potenciar los flujos donde el sistema ahorra más tiempo.",
    },
    tags: ["speed", "perception"],
    relatedMetricIds: ["usage-friction", "adopter-satisfaction"],
    icon: "Gauge",
    priority: 3,
  },
  {
    id: "perceived-quality",
    name: "Percepción de calidad",
    shortName: "Calidad",
    contextId: "design-systems",
    attributes: {
      categoria: "satisfaccion",
      measurementType: "qualitative",
      sourcePrimary: "research",
      figmaAvailability: "no",
      maturity: "classical",
      signalQuality: "medium",
      aiRelated: false,
    },
    ficha: {
      description: "Percepción de la solidez y acabado de los componentes del sistema.",
      whyItMatters: "La calidad percibida determina si los equipos usan o sustituyen los componentes.",
      howToMeasure: ["Escala de calidad por familia de componentes", "Comentarios abiertos sobre defectos"],
      frecuencia: "Trimestral",
      esfuerzo: "Medio",
      confianza: "Media",
      cruzarCon: ["Confianza en el sistema", "Percepción de consistencia"],
      risksBiases: ["Un componente defectuoso tiñe la percepción del conjunto"],
      audience: ["DS Team", "Design Leads"],
      decision: "Invertir en pulido de los componentes peor valorados.",
    },
    tags: ["quality", "perception"],
    relatedMetricIds: ["system-trust", "perceived-consistency"],
    icon: "ThumbsUp",
    priority: 3,
  },
  {
    id: "perceived-consistency",
    name: "Percepción de consistencia",
    shortName: "Consistencia",
    contextId: "design-systems",
    attributes: {
      categoria: "satisfaccion",
      measurementType: "qualitative",
      sourcePrimary: "research",
      figmaAvailability: "no",
      maturity: "classical",
      signalQuality: "medium",
      aiRelated: false,
    },
    ficha: {
      description: "Percepción de cuán coherente se siente el producto al usar el sistema.",
      whyItMatters: "La consistencia percibida refleja el valor del sistema para el usuario final.",
      howToMeasure: ["Encuesta sobre coherencia visual y de patrones", "Revisiones cualitativas de UI"],
      frecuencia: "Trimestral",
      esfuerzo: "Medio",
      confianza: "Media",
      cruzarCon: ["Percepción de calidad", "Claridad de reglas"],
      risksBiases: ["Difícil separar consistencia del sistema de decisiones de producto"],
      audience: ["DS Team", "Design Leads"],
      decision: "Detectar áreas donde la experiencia se percibe fragmentada.",
    },
    tags: ["consistency", "perception"],
    relatedMetricIds: ["perceived-quality", "rules-clarity"],
    icon: "Waves",
    priority: 3,
  },
  {
    id: "qualitative-feedback",
    name: "Feedback cualitativo",
    shortName: "Feedback",
    contextId: "design-systems",
    attributes: {
      categoria: "satisfaccion",
      measurementType: "qualitative",
      sourcePrimary: "research",
      figmaAvailability: "no",
      maturity: "classical",
      signalQuality: "weak",
      aiRelated: false,
    },
    ficha: {
      description: "Volumen y contenido de comentarios abiertos que los equipos dan sobre el sistema.",
      whyItMatters: "Aporta contexto y matices que las métricas cuantitativas no capturan.",
      howToMeasure: ["Recopilación de comentarios en encuestas y canales", "Codificación temática de respuestas"],
      frecuencia: "Continuo",
      esfuerzo: "Alto",
      confianza: "Baja",
      cruzarCon: ["Satisfacción de adopters", "Fricción de uso"],
      risksBiases: ["Ruido: los extremos hablan más que la mayoría silenciosa"],
      audience: ["DS Team"],
      decision: "Identificar temas recurrentes que orienten el roadmap.",
    },
    tags: ["feedback", "qualitative"],
    relatedMetricIds: ["adopter-satisfaction", "usage-friction"],
    icon: "Quote",
    priority: 2,
  },
  {
    id: "usage-friction",
    name: "Fricción de uso",
    shortName: "Fricción",
    contextId: "design-systems",
    attributes: {
      categoria: "satisfaccion",
      measurementType: "qualitative",
      sourcePrimary: "research",
      figmaAvailability: "no",
      maturity: "classical",
      signalQuality: "medium",
      aiRelated: false,
    },
    ficha: {
      description: "Dificultades y obstáculos que encuentran los equipos al usar el sistema.",
      whyItMatters: "La fricción no resuelta empuja a los equipos a soluciones fuera del sistema.",
      howToMeasure: ["Preguntas sobre barreras concretas", "Mapeo de puntos de dolor por flujo"],
      frecuencia: "Trimestral",
      esfuerzo: "Medio",
      confianza: "Media",
      cruzarCon: ["Satisfacción de adopters", "Percepción de velocidad", "Claridad de reglas"],
      risksBiases: ["Se reportan más las fricciones agudas que las crónicas asumidas"],
      audience: ["DS Team", "Design Leads"],
      decision: "Eliminar las barreras que más frenan la adopción.",
    },
    tags: ["friction", "usability"],
    relatedMetricIds: ["adopter-satisfaction", "perceived-speed"],
    icon: "AlertTriangle",
    priority: 4,
  },
  {
    id: "rules-clarity",
    name: "Claridad de reglas",
    shortName: "Claridad",
    contextId: "design-systems",
    attributes: {
      categoria: "satisfaccion",
      measurementType: "qualitative",
      sourcePrimary: "research",
      figmaAvailability: "no",
      maturity: "classical",
      signalQuality: "medium",
      aiRelated: false,
    },
    ficha: {
      description: "Percepción de cuán claras y comprensibles son las reglas y guías del sistema.",
      whyItMatters: "Reglas confusas generan usos incorrectos y decisiones inconsistentes.",
      howToMeasure: ["Encuesta sobre comprensión de guidelines", "Preguntas sobre dudas frecuentes"],
      frecuencia: "Trimestral",
      esfuerzo: "Bajo",
      confianza: "Media",
      cruzarCon: ["Percepción de consistencia", "Calidad percibida del soporte"],
      risksBiases: ["Quien no lee la documentación no percibe su falta de claridad"],
      audience: ["DS Team"],
      decision: "Reescribir las guías peor comprendidas.",
    },
    tags: ["clarity", "guidelines"],
    relatedMetricIds: ["perceived-consistency", "perceived-support-quality"],
    icon: "HelpCircle",
    priority: 3,
  },
  {
    id: "perceived-support-quality",
    name: "Calidad percibida del soporte",
    shortName: "Soporte",
    contextId: "design-systems",
    attributes: {
      categoria: "satisfaccion",
      measurementType: "qualitative",
      sourcePrimary: "research",
      figmaAvailability: "no",
      maturity: "classical",
      signalQuality: "medium",
      aiRelated: false,
    },
    ficha: {
      description: "Percepción de la utilidad y agilidad del soporte que ofrece el equipo de DS.",
      whyItMatters: "Un buen soporte sostiene la confianza y desbloquea a los equipos rápido.",
      howToMeasure: ["CSAT tras interacciones de soporte", "Tiempo percibido de respuesta"],
      frecuencia: "Trimestral",
      esfuerzo: "Bajo",
      confianza: "Media",
      cruzarCon: ["Confianza en el sistema", "Claridad de reglas"],
      risksBiases: ["Solo valora quien ha pedido soporte, no toda la base"],
      audience: ["DS Team", "Leadership"],
      decision: "Ajustar la capacidad y los canales de soporte según la percepción.",
    },
    tags: ["support", "perception"],
    relatedMetricIds: ["system-trust", "rules-clarity"],
    icon: "MessageCircle",
    priority: 3,
  },
];
